from .newsapi import run_newsapi
from .openweatherapi import run_openweatherapi
from .quotewebscrapping import run_quotewebscrapping
from .youtubedownload import run_youtubedownload
from .wallpaperwebscrapping import run_wallpaperwebscrapping
from .movieapi import run_movieapi
from .cryptocurrencyapi import run_crypto
from .stocksapi import run_stocks
from .hackathonswebscrsapping import run_hackathon
from .facebookloginwebscrapping import facebook
from .wikipediapi import run_wiki